apiVersion: apps/v1
kind: Deployment
metadata:
  name: useranalyticsservice
  labels:
    app: useranalyticsservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: useranalyticsservice
  template:
    metadata:
      labels:
        app: useranalyticsservice
    spec:
      containers:
      - name: useranalyticsservice
        image: alicanzeybek/useranalyticsservice:1.0
        ports:
        - containerPort: 14000
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: "/actuator/info"
            port: 14000
            scheme: "HTTP"
          initialDelaySeconds: 25
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        readinessProbe:
          failureThreshold: 3
          httpGet: 
            path: "/actuator/health"
            port: 14000
            scheme: "HTTP"
          initialDelaySeconds: 25
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: useranalyticsservice
  labels:
    app: useranalyticsservice
    spring-boot: "true"
spec:
  ports:
  - port: 14000
    protocol: TCP
  selector:
    app: useranalyticsservice
  type: ClusterIP
