apiVersion: apps/v1
kind: Deployment
metadata:
  name: redirectionservice
  labels:
    app: redirectionservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redirectionservice
  template:
    metadata:
      labels:
        app: redirectionservice
    spec:
      containers:
      - name: redirectionservice
        image: alicanzeybek/redirectionservice:1.0
        ports:
        - containerPort: 8080
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: "/actuator/info"
            port: 8080
            scheme: "HTTP"
          initialDelaySeconds: 25
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        readinessProbe:
          failureThreshold: 3
          httpGet: 
            path: "/actuator/health"
            port: 8080
            scheme: "HTTP"
          initialDelaySeconds: 25
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: redirectionservice
  labels:
    app: redirectionservice
    spring-boot: "true"
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: redirectionservice
  type: NodePort
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redirectionservice
data:
  application.yml: |-
    spring.datasource.url: jdbc:mariadb://vested-poodle-mariadb/cs443
    spring.datasource.username: root
    spring.datasource.password: UOZmH5SD63
