apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkretrievalservice
  labels:
    app: linkretrievalservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkretrievalservice
  template:
    metadata:
      labels:
        app: linkretrievalservice
    spec:
      containers:
      - name: linkretrievalservice
        image: alicanzeybek/linkretrievalservice:1.0
        ports:
        - containerPort: 8000
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: "/actuator/info"
            port: 8000
            scheme: "HTTP"
          initialDelaySeconds: 25
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        readinessProbe:
          failureThreshold: 3
          httpGet: 
            path: "/actuator/health"
            port: 8000
            scheme: "HTTP"
          initialDelaySeconds: 25
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: linkretrievalservice
  labels:
    app: linkretrievalservice
    spring-boot: "true"
spec:
  ports:
  - port: 8000
    protocol: TCP
  selector:
    app: linkretrievalservice
  type: NodePort
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: linkretrievalservice
data:
  application.yml: |-
    spring.datasource.url: jdbc:mariadb://vested-poodle-mariadb/cs443
    spring.datasource.username: root
    spring.datasource.password: UOZmH5SD63
