apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: gateway-ingress
spec:
  rules:
    - http:
        paths:
        - path: /user/*
          backend:
            serviceName: linkstoreservice
            servicePort: 8100
            
 
