apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkanalyticsservice
  labels:
    app: linkanalyticsservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkanalyticsservice
  template:
    metadata:
      labels:
        app: linkanalyticsservice
    spec:
      containers:
        - name: linkanalyticsservice
          image: alicanzeybek/linkanalyticsservice:1.0
          ports:
            - containerPort: 14200
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: "/actuator/info"
              port: 14200
              scheme: "HTTP"
            initialDelaySeconds: 25
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: "/actuator/health"
              port: 14200
              scheme: "HTTP"
            initialDelaySeconds: 25
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: linkanalyticsservice
  labels:
    app: linkanalyticsservice
    spring-boot: "true"
spec:
  ports:
    - port: 14200
      protocol: TCP
  selector:
    app: linkanalyticsservice
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: linkanalyticsservice
data:
  application.yml: |-
    spring.datasource.url: jdbc:mariadb://mariadb/cs443
    spring.datasource.username: root
    spring.datasource.password: UOZmH5SD63
