apiVersion: apps/v1
kind: Deployment
metadata:
  name: userpastlinkanalyticsretrievalservice
  labels:
    app: userpastlinkanalyticsretrievalservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userpastlinkanalyticsretrievalservice
  template:
    metadata:
      labels:
        app: userpastlinkanalyticsretrievalservice
    spec:
      containers:
      - name: userpastlinkanalyticsretrievalservice
        image: alicanzeybek/userpastlinkanalyticsretrievalservice:1.0
        ports:
        - containerPort: 14100
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: "/actuator/info"
            port: 14100
            scheme: "HTTP"
          initialDelaySeconds: 25
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        readinessProbe:
          failureThreshold: 3
          httpGet: 
            path: "/actuator/health"
            port: 14100
            scheme: "HTTP"
          initialDelaySeconds: 25
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: userpastlinkanalyticsretrievalservice
  labels:
    app: userpastlinkanalyticsretrievalservice
    spring-boot: "true"
spec:
  ports:
  - port: 14100
    protocol: TCP
  selector:
    app: userpastlinkanalyticsretrievalservice
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: userpastlinkanalyticsretrievalservice
data:
  application.yml: |-
    spring.datasource.url: jdbc:mariadb://mariadb/cs443
    spring.datasource.username: root
    spring.datasource.password: UOZmH5SD63
