spring:
  application:
    name: netflixzuulapigatewayserver

zuul:
  routes:
    auth-service:
      path: /auth/**
      service: AUTHSERVICE
      strip-prefix: false
  sensitive-headers: Cookie, Set-Cookie

server:
  port: 8765

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus,info,health
