apiVersion: apps/v1
kind: Deployment
metadata:
  name: authservice
  labels:
    app: authservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authservice
  template:
    metadata:
      labels:
        app: authservice
    spec:
      containers:
        - name: authservice
          image: alicanzeybek/authservice:1.0
          ports:
            - containerPort: 9100
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: "/actuator/info"
              port: 9100
              scheme: "HTTP"
            initialDelaySeconds: 25
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: "/actuator/health"
              port: 9100
              scheme: "HTTP"
            initialDelaySeconds: 25
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: authservice
  labels:
    app: authservice
    spring-boot: "true"
spec:
  ports:
    - port: 9100
      protocol: TCP
  selector:
    app: authservice
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authservice
data:
  application.yml: |-
    spring.datasource.url: jdbc:mariadb://mariadb/cs443
    spring.datasource.username: root
    spring.datasource.password: UOZmH5SD63
