apiVersion: apps/v1
kind: Deployment
metadata:
  name: userpastlinkanalyticsrearrangementservice
  labels:
    app: userpastlinkanalyticsrearrangementservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userpastlinkanalyticsrearrangementservice
  template:
    metadata:
      labels:
        app: userpastlinkanalyticsrearrangementservice
    spec:
      containers:
      - name: userpastlinkanalyticsrearrangementservice
        image: alicanzeybek/userpastlinkanalyticsrearrangementservice:1.0
        ports:
        - containerPort: 14300
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: "/actuator/info"
            port: 14300
            scheme: "HTTP"
          initialDelaySeconds: 25
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        readinessProbe:
          failureThreshold: 3
          httpGet: 
            path: "/actuator/health"
            port: 14300
            scheme: "HTTP"
          initialDelaySeconds: 25
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: userpastlinkanalyticsrearrangementservice
  labels:
    app: userpastlinkanalyticsrearrangementservice
    spring-boot: "true"
spec:
  ports:
  - port: 14300
    protocol: TCP
  selector:
    app: userpastlinkanalyticsrearrangementservice
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: userpastlinkanalyticsrearrangementservice
data:
  application.yml: |-
    spring.datasource.url: jdbc:mariadb://mariadb/cs443
    spring.datasource.username: root
    spring.datasource.password: UOZmH5SD63
